site_name: Oliver Twist

repo_name: 'oliver-twist'
repo_url: 'https://github.com/autotraderuk/oliver-twist'

theme:
  name: 'material'
  logo: 'images/oliver_twist_logo.svg'
  favicon: 'images/favicon.ico'
  custom_dir: 'docs/overrides'

extra_css:
  - css/extra.css
  - css/font-awesome/css/all.css  
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

markdown_extensions:
  - attr_list
  - meta
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
