
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.md')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='olivertwist',
    version='0.2',
    description='DBT DAG Auditor',
    python_requires='==3.*,>=3.6.0',
    project_urls={"homepage": "http://olivertwi.st", "repository": "https://github.com/autotraderuk/oliver-twist"},
    author='Angelos Georgiadis',
    author_email='angelos.georgiadis@autotrader.co.uk',
    maintainer='Paul Doran',
    maintainer_email='paul.doran@autotrader.co.uk',
    license='Apache-2.0',
    entry_points={"console_scripts": ["olivertwist = olivertwist.main:main", "ot = olivertwist.main:main"]},
    packages=['olivertwist', 'olivertwist.config', 'olivertwist.metricengine', 'olivertwist.reporter', 'olivertwist.ruleengine', 'olivertwist.rules'],
    package_dir={"": "."},
    package_data={"olivertwist.reporter": ["html/css/*.css", "html/images/*.svg", "html/webfonts/*.eot", "html/webfonts/*.svg", "html/webfonts/*.ttf", "html/webfonts/*.woff", "html/webfonts/*.woff2", "templates/*.html", "templates/*.jinja"]},
    install_requires=['click==7.*,>=7.1.2', 'colorama<0.4.4', 'dataclasses==0.*,>=0.8.0; python_version == "3.6.*" and python_version >= "3.6.0"', 'dataclasses-jsonschema==2.*,>=2.13.0', 'flake8-bugbear==20.*,>=20.11.1', 'jinja2==2.11.3', 'networkx==2.*,>=2.5.0', 'pyinquirer==1.*,>=1.0.3', 'pyyaml==5.*,>=5.3.1', 'scipy'],
    extras_require={"dev": ["black==20.*,>=20.8.0.b1", "flake8==3.*,>=3.8.4", "mkdocs==1.*,>=1.1.2", "mkdocs-material==6.*,>=6.2.3", "pre-commit==2.*,>=2.9.0; python_version == \"3.*\" and python_version >= \"3.6.1\"", "pymdown-extensions==8.*,>=8.1.0", "pytest==6.*,>=6.2.0"]},
)
